### ISSUE TITLE
Posterior sample CMB T maps?

### ISSUE THREAD

**Issue by drphilmarshall** [rogerblandford/Music#10]
Hi @hke!

I think we are ready for a sample of posterior sample Planck temperature maps! @rogerblandford has checked that his treatment of the `alm`'s matches `healpy`'s, and is moving on to the potential reconstruction. Would you mind putting let's say 100 posterior sample maps, in the same format as the one on the Planck wiki at http://pla.esac.esa.int/pla/aio/product-action?MAP.MAP_ID=COM_CompMap_CMB-commrul_0256_R1.00.fits , on a website somewhere? Then I can download them, do the SH decomposition and give them to Roger. He's on a tight deadline: due to give a talk on this on Tuesday! Anything you can do for us on this timescale would be really great.

Thanks very much!

Phil

**Comment by hke** [comment]
Hi Phil,

I'm forwarding this email to Ingunn -- she should have the samples you 
need, I think.

Ingunn -- can you please find 100 Nside=256, Planck+ext samples, and put 
them on your webpage, so Phil can access them?

Thanks!

Hans Kristian

Den 28. aug. 2015 22:22, skrev Phil Marshall:

**Comment by hke** [comment]
Hi Phil,

100 CMB samples from the Commander 32-band (Planck+WMAP+Haslam) runs can now be found here:

http://folk.uio.no/ingunnkw/planck/32band/commander_32band_Clsamples100.tar.gz

The maps are at Healpix nside=256, 1 degree resolution, and are in thermodynamic uK.

Thanks,

Ingunn

**Comment by rogerblandford** [comment]
Many thanks,
Hans-Kristian and Ingunn.
Roger
On Aug 28, 2015, at 2:15 PM, Hans Kristian Eriksen <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Phil,

100 CMB samples from the Commander 32-band (Planck+WMAP+Haslam) runs can now be found here:

http://folk.uio.no/ingunnkw/planck/32band/commander_32band_Clsamples100.tar.gz

The maps are at Healpix nside=256, 1 degree resolution, and are in thermodynamic uK.

Thanks,

Ingunn

**Comment by drphilmarshall** [comment]
Excellent! Thanks @hke. I have decomposed them all for Roger, and am taking a look at them in [this new notebook](https://github.com/drphilmarshall/Music/blob/master/PlanckSamples_Demo.ipynb). I _think_ I can see differences between them, but man, Planck is good data.

**Comment by ingunnkw** [comment]
If you only look at l<10 the maps should look very similar. We use Planck data from 93% of the sky. The remaining 7% in the Galactic plane is filled with a constrained realization.

**Comment by drphilmarshall** [comment]
Interesting! At some point we'll have to learn more about that, and make
some decisions about whether or not to mask that 7%. My guess is that it
won't matter much, and using the whole map is fine. Thanks very much for
the maps, Ingunn! :-)

**Comment by rogerblandford** [comment]
For the moment I see no advantage in masking the zoa.
Trying to improve what I know is already a very careful procedure will take us even further from our area of competence!
If you can produce the other 99 files without the headers, I think I can see what to do next, but it would be great if you could compute the means variances and covariances.
Hope Kids’ night went well.
Roger
On Aug 28, 2015, at 10:08 PM, Phil Marshall <notifications@github.com<mailto:notifications@github.com>> wrote:

Interesting! At some point we'll have to learn more about that, and make
some decisions about whether or not to mask that 7%. My guess is that it
won't matter much, and using the whole map is fine. Thanks very much for
the maps, Ingunn! :-)

**Comment by drphilmarshall** [comment]
Alright, check out the [Planck samples notebook here](https://github.com/drphilmarshall/Music/blob/master/PlanckSamples_Demo.ipynb) - I plotted up the `alm` coefficients from Ingunn's sample maps to look for correlations, there's some interesting patterns. A Laplace approximation actually looks like it'll work well, which is good because we've been a bit nervous about trying to invert the response matrix that connects the 3D potential Fourier coefficients with the temperature map `alm`'s. The first thing we'll try is an inversion that included the Gaussian uncertainties on the `alm`'s, which should be a bit more stable, numerically, I think.

Roger,  I've written out the mean `alm` array, and its covariance matrix for you to play around with. Please see my notes at https://github.com/drphilmarshall/Music/blob/master/PlanckSamples_Demo.ipynb: I'm only writing out the positive `m`'s, and I think our response (R) matrix needs to work under the same restriction, producing only a minimal set of Fourier coefficients... That way we will enforce a real potential. I'll email you the means and covariance files.

**Comment by drphilmarshall** [comment]
Iterating on the covariance matrix: separating real and imaginary parts (in order to preserve the covariance of these measurements) gives a pretty ill-conditioned covariance matrix. Ignoring the imaginary parts of the `m=0` coefficients improves matters to some extent, but doesn't solve the problem. Hopefully multiplying by the response matrix and inverting by SVD will be stable. 

My notes are in https://github.com/rogerblandford/Music/blob/master/PlanckSamples_Demo.ipynb and the "edited, separated" mean `alm`'s and covariance matrix can be downloaded from: 

https://github.com/rogerblandford/Music/blob/master/data/commander_32band_Clsamples100_mean_edited_separated.txt

https://github.com/rogerblandford/Music/blob/master/data/commander_32band_Clsamples100_cov_edited_separated.txt

**Comment by drphilmarshall** [comment]
Roger, there's a [pseudo-inverse](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.pinv.html) of `C`  in https://github.com/rogerblandford/Music/blob/master/data/commander_32band_Clsamples100_inverse_cov_edited_separated.txt for you to play with. Singular values less than `1e-15` were reset to zero. Good luck!
