### ISSUE TITLE
PGMs for initial inferences

### ISSUE THREAD

**Issue by drphilmarshall** [rogerblandford/Music#11]
Hi @LaurencePeanuts - I made some figures for you, probabilistic graphical models of the inference we drew on my white board on Friday. They'll look nice in the latex where you define the $\eta$ hyperparameter vector! [Here's the notebook](https://raw.githubusercontent.com/rogerblandford/Music/master/doc/pgm/inflation.png), and I checked this and the png images into the `doc/pgm` folder. Hope you like them!

![PGM for slow roll inflation inference](https://github.com/rogerblandford/Music/blob/master/doc/pgm/inflation.png)

**Comment by LaurencePeanuts** [comment]
Hi Phil,

Thanks!
They look great! I'll try to post an updated version of the latex inflation
file today!

Best,
Laurence

2015-09-10 15:53 GMT-07:00 Phil Marshall notifications@github.com:

**Comment by rogerblandford** [comment]
Looks good.
Let’s get together next week.
Roger
On Sep 11, 2015, at 11:18 AM, LaurencePeanuts <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Phil,

Thanks!
They look great! I'll try to post an updated version of the latex inflation
file today!

Best,
Laurence

2015-09-10 15:53 GMT-07:00 Phil Marshall <notifications@github.com<mailto:notifications@github.com>>:

**Comment by drphilmarshall** [comment]
[Laurence's notes](https://github.com/rogerblandford/Music/blob/master/doc/Link_to_Inflation.pdf) now include two very nice PGMs, so we can close this out.
