### ISSUE TITLE
Bib file for the 2015 NSF proposal

### ISSUE THREAD

**Issue by LaurencePeanuts** [rogerblandford/Music#16]
Hi @rogerblandford & @drphilmarshall 

I'm a trying to find a bib file for the proposal to add my references to, but from what I can see there isn't one yet? Is that correct? I'll start a new one now, and try to find a bib style that follows the guidelines Roger sent:

"Reference information is required. Each reference must include the names of all authors (in the same sequence in which they appear in the publication), the article and journal title, book title, volume number, page numbers, and year of publication. If the document is available electronically, the website address also should be identified. Proposers must be especially careful to follow accepted scholarly practices in providing citations for source materials relied upon when preparing any section of the proposal. While there is no established page limitation for the references, this section must include bibliographic citations only and must not be used to provide parenthetical information outside of the 15-page Project Description."

For the website address, is the arxiv reference good enough?

Thanks!
Laurence

**Comment by drphilmarshall** [comment]
This got done in the proposal rush, and should help with both music.tex, the link to inflation notes, and any paper we write. I'll copy it to `music.bib` and close this issue.
