### ISSUE TITLE
Roland's visit to KIPAC: Music discussion

### ISSUE THREAD

**Issue by drphilmarshall** [rogerblandford/Music#17]
@rdputter Great to see you this morning, really enjoyed your cosmology seminar :-) Would you be able to put your slides online somewhere for Roger to catch up on? He's out of town this week, unfortunately.

As you can see, the Music project has moved on a fair bit since the Berkeley hack week. @rogerblandford is working on our first 3D potential reconstruction in a feasibility study (he has found stable combinations of kmax and lmax that should enable maps to be made). Meanwhile, Laurence Perrault Levasseur ( @LaurencePeanuts ) has been working through the hierarchical inference of slow roll parameters given CMB data - you'll like this I think, check out [her notes](https://github.com/rogerblandford/Music/blob/master/doc/Link_to_Inflation.pdf). 

It's good that you're here tomorrow too: let's meet up with Laurence and chat more, it'd be great to get your take on the potential (hah!) of SphereX and other surveys, and baby steps we might take in exploring it. How does 10am, before KIPAC tea, sound? We can meet in Roger's office in the PAB and lament his absence.

Cheers

Phil

**Comment by rdputter** [comment]
Hi Phil,

Thanks for the update on the Music of the Sphere project. It will be great
to chat more about this tomorrow. I am already meeting someone at 10am
though. Could we do another time? Perhaps right after KIPAC tea?

Here is a link to a Dropbox folder containing a pdf of my slideshow:

**Comment by rdputter** [comment]
accidentally sent that email too soon, here is the actual link:

https://www.dropbox.com/sh/x1u466w3m6qud9t/AAC24HIImZtai7D-z-HwCo7Ta?dl=0

Cheers,
Roland

**Comment by LaurencePeanuts** [comment]
Hi @rdputter 

Thanks for the slides! Yes, meeting right after KIPAC tea sounds great.
Looking forward to it!

Best wishes,
Laurence

**Comment by drphilmarshall** [comment]
Good to see you yesterday, @rdputter ! Here are the ideas that came up, for things for us to investigate:
- Let's draw some 3D potential fields with a) Fourier amplitudes coming from the standard inflation model power spectrum but b) Fourier phases coming from articifially non-uniform distributions of various kinds. Many different patterns in the complex plane can be imagined - would we detect them in the CMB T data if they were there?
- What does the local non-Gaussianity $f_{nl}$ formalism imply in terms of the prior PDF for the Fourier amplitudes? Is this a computationally feasible prior to use? Could it be approximated by something that is computationally feasible?
- What is the physical meaning of, say, a two component Gaussian mixture model for the prior PDF for Fourier amplitudes? This is a non-Gaussian prior that we could use, while preserving the linearity of the model for computational reasons...

**Comment by drphilmarshall** [comment]
@LaurencePeanuts I am going to close this "discussion" issue for now. Let's refer to it later, when we issue ourselves with working on any one of the three ideas above. This will probably be after we've got our python map making code working :-)
