### ISSUE TITLE
Current draft needs checking in 

### ISSUE THREAD

**Issue by rogerblandford** [rogerblandford/Music#2]

**Comment by drphilmarshall** [comment]
There is now an audience of engaged hackers for your notes! :-)

**Comment by rogerblandford** [comment]
Hi
Not had much time to rebuild what I wrote and am still confused on several points
but what I had focused on was off in a rather different direction.
This is very sketchy and the figures are not done.
No way can I absorb what you have unleashed.
Not sure this is ready for github.
Roger

**Comment by rogerblandford** [comment]
Sketchy is good - nothing we are doing this week is anything else! I'm not
sure how much will get built this week, but Ryan's group have started a
useful python framework, and Michael's group are re-working some
Wandelt-esque math. I think it will all come together well, and within your
vision. Thanks for the attachment - its not visible from github, as you
say, but Ryan and I can take a look tomorrow.
