### ISSUE TITLE
Response matrix

### ISSUE THREAD

**Issue by drphilmarshall** [rogerblandford/Music#20]
First test: generate a phi field, and compute the corresponding T map and display it. Should be fun! :-)

**Comment by LaurencePeanuts** [comment]
Hi @drphilmarshall 
I've generated maps, but there is an issue that I'm struggling to understand... From the way healpy stores a_lm's it looks like the negative m's are thrown out...? To me it also looks like the way the get_alm function is build, all the negative m's are dependent on the positive m's... so there isn't really 2l+1 independent ms for each l...  am I right or am I missing something?

Thanks!
Laurence

**Comment by drphilmarshall** [comment]
No, that's right - the negative m's have to depend on the positive ones in
such a way as to make the temperature maps everywhere real. As far as I
know, my `get_alm` function does the right thing...

**Comment by rogerblandford** [comment]
Yes. I reorganize them to give my a_y the coefficients of real spherical harmonics Y_y.
Roger
On Dec 8, 2015, at 5:09 PM, Phil Marshall <notifications@github.com<mailto:notifications@github.com>> wrote:

No, that's right - the negative m's have to depend on the positive ones in
such a way as to make the temperature maps everywhere real. As far as I
know, my `get_alm` function does the right thing...

**Comment by LaurencePeanuts** [comment]
Great! That right we need a real sky! that's a good sign for the R matrix
and the ay that the python code generate since, now that I'm looking at it,
for each l the ay have: ay for -m equal to (-1)^(m)*(ay for m)^\dagger .
I guess I didn't have much intuition for real spherical harmonics...
Looks like there is still some debugging to though... I can make T maps but
haven't figured how to recover sensible a_lms from them (yet).

Best,
Laurence

2015-12-08 17:29 GMT-08:00 Roger Blandford notifications@github.com:

> Yes. I reorganize them to give my a_y the coefficients of real spherical
> harmonics Y_y.
> Roger
> On Dec 8, 2015, at 5:09 PM, Phil Marshall <notifications@github.com

**Comment by drphilmarshall** [comment]
Do you mean that when you use the healpy `map2alm` function you get a_lm's
that are non-sensible? In what way?

**Comment by LaurencePeanuts** [comment]
Yeah, they are pretty much zero. The monopole should be zero, but it returns dipole components between 1e-20 and 1e-37 while they should be around 1e-5. Same thing goes for pretty much all the multipoles. I'm sure I'm doing something stupid though...

**Comment by drphilmarshall** [comment]
Hey @LaurencePeanuts ! Show us a T-map :-)

**Comment by drphilmarshall** [comment]
Scratch that - you already did, in #8 :-)

**Comment by LaurencePeanuts** [comment]
Just for reference, the T-maps are in [this notebook](https://github.com/rogerblandford/Music/blob/master/Potential_Demo.ipynb) .
