### ISSUE TITLE
The demo notebooks need some cleaning up + updating

### ISSUE THREAD

**Issue by LaurencePeanuts** [rogerblandford/Music#24]
Almost all of the demo notebooks need some serious updating to make sure they still run with the current version of the code. Should the [Beatbox_Demo.ipynb](https://github.com/rogerblandford/Music/blob/master/Beatbox_Demo.ipyn) notebook be deleted?

**Comment by drphilmarshall** [comment]
I think so - it would be good to have a very small number of well-named
demos, that just serve to show what we are doing. I think we want:
- A notebook that shows how we can recover an input 3D potential, from mock
  CMB T data (and maybe also shows the situation where our method breaks
  down): Reconstruction.ipynb ?
- A notebook that shows our best estimate of the 3D potential from the real
  Planck CMB T data, and some checks and visualizations. Planck.ipynb ?

What do you think? Do we have other results that we should display in this
way?

**Comment by LaurencePeanuts** [comment]
I was thinking it would be good to keep the [Potential_Demo](https://github.com/rogerblandford/Music/blob/master/Demos/Potential_Demo.ipynb) notebook, since it shows the different way we can display the 3d potential and the 2d maps. It's a good place to play around with color maps and the ways of representing the CMB sphere in 3d. It also shows that from Roger's set of f_n generated with mathematica, the python code can produce the correct 2d CMB temperature map. I agree it's not a groundbreaking result, but it's a good consistency test between the Mathematica and Python codes. What do you think? Right now I think it's more or less presentable.

About the [Reconstruction_Demo](https://github.com/rogerblandford/Music/blob/master/Demos/Reconstruction_Demo.ipynb) notebook, at the moment it has 3 parts: 1. reconstruction using the mock data generated by the python code, 2. reconstruction using the mock data generated by Roger's Mathematica code, and 3. reconstruction using one of the Planck samples as data. I thought it was pretty neat that way, but if you think it's better then I can split it in two separate notebooks. 

Is there anything from the current PlanckSamples_Demo that we should keep and put in a Planck_Demo notebook? for example, the visualisations of the covariance matrix, etc...?

**Comment by drphilmarshall** [comment]
Yeah, maybe - a short demo notebook showing how we deal with the Commander
maps would be useful. It can stop after showing the covariance matrix,
though. The other two look good, I think - the reconstruction demo title
shoudl be something mroe general now it has real data in it! :-)

**Comment by LaurencePeanuts** [comment]
I fixed the title for the reconstruction demo, and now all notebooks should run from inside the [Demos](https://github.com/rogerblandford/Music/tree/master/Demos) folder, provided people add the Music folder to their Python path .

**Comment by drphilmarshall** [comment]
Bravo! Thanks Laurence :-)

**Comment by LaurencePeanuts** [comment]
I did something with [PlanckSamples_Demo](https://github.com/rogerblandford/Music/blob/master/Demos/PlanckSamples_Demo.ipynb). Is that what you had in mind? I also added a reconstruction from a mock with l_max=30 at the end because I thought it was relevant to show that even with the ill-conditioned covariance matrix, the reconstruction seems to work pretty well (most probably because of the prior). If you don't think that should be there then I can also move it elsewhere.

There is also a [Scripts](https://github.com/rogerblandford/Music/tree/master/Scripts) folder now, so the reconstruction script should run from there. As I add new scripts I'll put them in there, too.

Now I think the [README.md](https://github.com/rogerblandford/Music/blob/master/README.md) file is the one that needs updating the most? Its figure seems to have disappeared a long time ago and it should mention that one needs to add the Music folder to their python path in order to run either the scripts or the demos. The links in the Activities section are also broken (a bit my fault since I moved the demos around).

**Comment by drphilmarshall** [comment]
Great stuff, Laurence! I love the lmax = 30 SVD stress test: amazing that
it can recover from such an extremely ill-conditioned covariance matrix,
that bodes well for our robustness tests/grid. And you can really see the
increased uncertainty in the galactic plane region! Very cool.  Now: how
are the singular values being treated, here? Presumably many are being set
to zero, but can you explain how many and by what criteria?

Agreed: README is the next thing to be cleaned up. I suggest it only
include one, high value figure, and then explanatory text that is as brief
as possible. Then you can close this out I think! :-)

**Comment by LaurencePeanuts** [comment]
I'm just using SVD to calculate the pseudo inverse and then that's what I use for the whole reconstruction process (also for generating noise for the mock), basically step 1.a) of issue #21. ( as a side note, the noise seems very large because the normalization of my power spectrum isn't quite right yet since I haven't fixed #23, but it's not really important for this discussion)

What's a 'high value figure'?

**Comment by drphilmarshall** [comment]
Interesting: I see from [line 176 of `multiverse.py`](https://github.com/rogerblandford/Music/blob/master/beatbox/multiverse.py#L176) that you are not filtering the singular values at all - and I don't think the `np.linalg.svd` does any thresholding. The [`numpy.linalg.pinv`](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_pseudoinverse#Singular_value_decomposition_.28SVD.29) does round off the singular values that are below machine precision to zero; can you explain why you get stable pseudo inverses without using the `pinv` routine?

**Comment by drphilmarshall** [comment]
PS. "High value figure" means the same as "killer plot" but I am trying not to use violent metaphors! :-)

**Comment by LaurencePeanuts** [comment]
I'm still unsure about what a 'killer plot' is. I'm a theorist, so I regard a graph drawn with paint of scalar field values, or even better, hand drawn, as valid things to put in papers... I'm guessing you mean either something that looks very cool, like something 3d, or something that has a lot of impressive information summed up in it... ?

**Comment by drphilmarshall** [comment]
Both of these things would be ideal! It's just advertizing though, so just
pick something cool and go with that.

**Comment by LaurencePeanuts** [comment]
To answer your previous question, my understanding is that the s vector that SVD returns (the vector of singular values) has all singular values that correspond to zero, negative, and/or complex eigenvalues replaced by something $\mathcal{O}(10^{-14}-10^{-15})$ (i.e. effectively 0), which is what I assume you mean by 'thresholding'. The SVD inverse for such an ill-defined matrix is not great (by which I mean C_yy^-1*C_yy close-ish to **1** only by blurring your eyes quite a lot). 

However, there are 2 reasons why regardless of this, the most probable $f_n$ we recover seem to make sense. 

-First, if the prior is strong enough, then it has large enough e-values to make the **A** matrix stable when we invert it, and the inverse of **A** is the really important piece when it comes to solving for the most probable value. 

-When, on the other hand, I make the prior very small (by multiplying it by a overall small constant), then **A** becomes dominated by $C_{yy}^{-1}$, and because $C_{yy}^{-1}+\epsilon$ is singular (just like $C_{yy}^{-1}$), then again I have to use SVD to invert **A** (as opposed to just using $C_{yy}$ by itself). The trick here is that the SVD inverse of (the $C_{yy}^{-1}$ calculated with SVD) is a pretty good inverse of  (the $C_{yy}^{-1}$ calculated with SVD), even if  $C_{yy}$ and (the $C_{yy}^{-1}$ calculated SVD) are not very good inverses of each other. 
In this case, in theory $C_{yy}$ doesn't even enter in the calculation of the most probable $f_n$, so the fact that I end up using matrices that are good inverses of each other makes them cancel out relatively well and we can recover the mock $f_n$'s correctly. 

I think that in fact we are somehow in between these two cases in terms of the strength of the prior. I agree that this is convoluted and sounds worrying, but we know that we should really be using a covariance matrix calculated from more samples at such high $l_{max}$ anyway.... We should talk about his more...

**Comment by LaurencePeanuts** [comment]
@drphilmarshall, if you are happy with the current README file I'll close this issue. I haven't done much to it but at least now the links work and make sense.

**Comment by drphilmarshall** [comment]
Looks good to me! The tiff wasn't displaying (too big!) so I replaced it with a jpg. Very nice :-)

Funny how we seem to be in the middle of a slight potential dip, eh? I wonder if that will go away when the ISW effect is taken into account?

**Comment by LaurencePeanuts** [comment]
Ok great, thanks!
Yeah I was wondering the same thing (how robust that dip is...). Time will tell!
