### ISSUE TITLE
The 3D rendering with yt needs a new colormap

### ISSUE THREAD

**Issue by LaurencePeanuts** [rogerblandford/Music#25]
It would be best to have a colormap with black for 0 density instead of white as it is now. There are some examples of how to make a custom colormap [here](http://scipy-cookbook.readthedocs.org/items/Matplotlib_Show_colormaps.html). 
Also the sphere that represents the CMB sphere in the 3d volume should be thinner, but for this to work well the resolution of the x grid needs to be increased (or needs to be defined in polar coordinates).

**Comment by drphilmarshall** [comment]
Have you talked to Ralf Kaehler (next door to me) about displaying density
fields in this way? He's thought a lot about color maps I think, and might
have some good advice for you.

**Comment by LaurencePeanuts** [comment]
No I haven't, but I will! Thanks!
It would be good to have a color bar on the volume renderings too. Something like what the method  save_annotated() of the camera object in yt does. For now I haven't really managed to make it work... see example [here](http://yt-project.org/doc/cookbook/complex_plots.html#cookbook-amrkdtree-downsampling).

**Comment by drphilmarshall** [comment]
I agree, color bars are important. I just called in on Ralf - he said he'd be happy to play around with visualizing your maps, he just needs the 3D numpy array of the map output as a binary file and sent to him. Try something like:

``` python
np.save(outfile, x)
```

in a suitably named method in the `Universe` class? He didn't have a go-to color bar with white background, but he did suggest we 1) avoid `Jet` and 2) try red/white/blue with limits set such that zero maps to white. If you have French family they'll like this idea I think. Looks like [`RdBu_r`](http://yt-project.org/doc/visualizing/plots.html#colormaps) might do the trick.

**Comment by LaurencePeanuts** [comment]
Yes, with the with background instead of the black background, looks like RdBu_r is a winner for paper purposes. However, it looks like there is no great pre-made colormap that works for black backgrounds, which was the original point of this issue. I'll still close the issue for now since we won't need it for paper 1 arXiv submission.

**Comment by drphilmarshall** [comment]
Great! I think your white background 3D figures look good.
