### ISSUE TITLE
Ryan's python code needs to be merged back in

### ISSUE THREAD

**Issue by drphilmarshall** [rogerblandford/Music#4]
Hey @rkeisler , hope things are going well! I'm going to try and understand what your python code does as I merge it into the base repo (I know you don't have time to submit pull requests :-)) If I hit things I don't understand, which is best, private email or issues here? Thanks!

**Comment by rkeisler** [comment]
Hey @drphilmarshall.  Talking here on github should work.

**Comment by drphilmarshall** [comment]
Great! I started by simply merging and then tidying: all the notes written
at CtU2015 are now in the same document, in a doc directory. I'll probably
leave them as they are for posterity, and then merge content into
@rogerblandford's latex when he checks it in. He's working on the response
function between a potential modeled with a truncated 3D fourier series,
and the CMB a-lm's. I'll then revisit the inverse problem, and see about
extending the beatbox into 3D. That's the rough plan, anyway!

**Comment by rogerblandford** [comment]
Good.
Let’s get together Monday.
Where will you be?
Roger
On Aug 23, 2015, at 3:48 PM, Phil Marshall <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #4https://github.com/rogerblandford/Music/issues/4.

**Comment by drphilmarshall** [comment]
I'll be at SLAC all day Monday, come and find me when you get in. I'm going to merge some CtU2015 latex into music.tex first thing, and then I think we should try and pair-code the generation of the potential coefficients from the $a_lm$'s now that we have them (see the notebook linked from https://github.com/rogerblandford/Music/pull/7).
