### ISSUE TITLE
ROSES ATP proposal needs updating for theory+commenting 

### ISSUE THREAD

**Issue by LaurencePeanuts** [rogerblandford/Music#44]
Hi @drphilmarshall and @rogerblandford,  

I've started to edit the new project description for the ROSES theory proposal [here](https://github.com/rogerblandford/Music/blob/master/doc/proposals/2016NASAtheory/prodes.pdf). The proposal is a couple lines too long (over 15 pages) in its current state. I've added things about future surveys, the fact that we know Planck polarization data will exist soon-ish, some more emphasis that learning things about the inflationary potential is an important theoretical thing to do (I think maybe that wasn't clear before), but I have not included the paragraph about the EFT of LSS because I didn't think it would add much to our case (it's commented in the tex file so it would be very easy to re-include it). Apart from the project description and the abstract (which I haven't touched) I think everything can remain the same. 

I am leaving Saturday for Asia so I was really hoping finishing the bulk part of this before then :)

Best,
Laurence

**Comment by drphilmarshall** [comment]
Great, thanks Laurence! Roger and I are going to look at this this
afternoon. Can you skype with us at 2pm please?

**Comment by drphilmarshall** [comment]
Hi @rogerblandford  - git pull, I just added a bio in `doc/proposals/2016NASAtheory/PhilMarshall_NASA-bio.pdf`

**Comment by LaurencePeanuts** [comment]
Hi @rogerblandford  - git pull again, I just changed the table of personnel in doc/proposals/2016NASAtheory/tableofpersonelandworkeffort_letterofcommitment.pdf
and 
doc/proposals/2016NASAtheory/tableofpersonelandworkeffort_letterofcommitment.docx

**Comment by LaurencePeanuts** [comment]
There is a section in the proposal called 'Data Management', and here's what we have written for it:

Data Management
The primary dataset that is being used for this project derives from the Planck satellite. The data sets that are needed have already been downloaded and used to infer the results so far that we describe. Two leading Planck scientists have been advising us on occasional queries. As our interest is confined to low l modes, the overall computing needs have been modest so far.
The generalization to include additional date sets and more complex MCMC searches will be more demanding but well within the scope of the computational resources to which we have access. There is local expertise, which we intend to tap, on essentially all of the surveys that we shall use with the important exception of WISE where we intend to consult with senior members of the research team.

If that's good then we can just tell Ziba not to change it, but otherwise it'll need updating.

**Comment by drphilmarshall** [comment]
I just finished editing the project description and summary, git pull to see my updates. I'll email them to Ziba as well, and then pass back to you, @rogerblandford, in case there are any last minute additions you want to make.
