### ISSUE TITLE
Planck data

### ISSUE THREAD

**Issue by drphilmarshall** [rogerblandford/Music#6]
We need the temperature $a_{lm}$'s and their covariance matrix. I'll see what I can find.

**Comment by drphilmarshall** [comment]
Hmm. Looks like the $a_{lm}$'s are not available. The [Planck Legacy Archive documentation](http://wiki.cosmos.esa.int/planckpla2015/index.php/Sky_temperature_maps) argue that we should be working from sky maps:

> Sky maps give the best estimate of the intensity and polarization (Stokes Q and U components), if available, of the signal from the sky after removal, as far as possible, of known systematic effects (mostly instrumental, but including also the solar and earth-motion dipole, Galactic stray light and the Zodiacal light).

I think we should follow the prescription for computing the [low ell likelihood described here](http://wiki.cosmos.esa.int/planckpla2015/index.php/CMB_spectrum_%26_Likelihood_Code#Low-.E2.84.93_likelihoods). I'll download the [baseline data and code](http://pla.esac.esa.int/pla/#cosmology) and play around a bit. @rkeisler, do you have python code for handling Planck-formatted data? Looks like it'll be important to follow their Healpix and FITS conventions.

**Comment by rogerblandford** [comment]
I knew this but still think that the T->Y->\tilde\Phi is a good approach.
(I played with healpix ab initio just to try to understand what they were doing.)
The non-parametric tree route presents another approach.
Roger
On Aug 3, 2015, at 6:01 AM, Phil Marshall <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmm. Looks like the $a_{lm}$'s are not available. The Planck Legacy Archive documentationhttp://wiki.cosmos.esa.int/planckpla2015/index.php/Sky_temperature_maps argue that we should be working from sky maps:

Sky maps give the best estimate of the intensity and polarization (Stokes Q and U components), if available, of the signal from the sky after removal, as far as possible, of known systematic effects (mostly instrumental, but including also the solar and earth-motion dipole, Galactic stray light and the Zodiacal light).

I think we should follow the prescription for computing the low ell likelihood described herehttp://wiki.cosmos.esa.int/planckpla2015/index.php/CMB_spectrum_%26_Likelihood_Code#Low-.E2.84.93_likelihoods. I'll download the baseline data and codehttp://pla.esac.esa.int/pla/#cosmology and play around a bit. @rkeislerhttps://github.com/rkeisler, do you have python code for handling Planck-formatted data? Looks like it'll be important to follow their Healpix and FITS conventions.

**Comment by drphilmarshall** [comment]
Agreed - working with maps will take some work to understand the inner workings of the Planck likelihood code. I'll as around for the $a_{lm}$'s.

**Comment by rkeisler** [comment]
healpy is good for interacting with Planck FITS files and doing spherical
harmonic transforms.

See https://github.com/rkeisler/vksz/blob/master/vksz.py for some examples.

Ryan

**Comment by drphilmarshall** [comment]
Thanks @rkeisler, that's super useful.  I see you don't seem to use the
variance maps that come as one of the HDUs of the Planck FITS files - what
do you make of these? I was surprised to see that its only a variance map
that's provided, and not a covariance matrix...

**Comment by rogerblandford** [comment]
Sitting in on high minded session on statistics of exoplanets. Interesting but large gaps between philosophy and data.

Of course, as we discussed, we can skip the Ys and just go from HEALPIX to k-space maybe we should get similar answers from both but it is much easier to calculate using Ys.
Roger

Sent from my iPhone

On Aug 3, 2015, at 08:24, Phil Marshall <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks @rkeisler, that's super useful. I see you don't seem to use the
variance maps that come as one of the HDUs of the Planck FITS files - what
do you make of these? I was surprised to see that its only a variance map
that's provided, and not a covariance matrix...

On Mon, Aug 3, 2015 at 10:32 AM, Ryan Keisler <notifications@github.com<mailto:notifications@github.com>>
wrote:

> healpy is good for interacting with Planck FITS files and doing spherical
> harmonic transforms.
> 
> See https://github.com/rkeisler/vksz/blob/master/vksz.py for some
> examples.
> 
> Ryan
> 
> On Mon, Aug 3, 2015 at 9:01 AM, Phil Marshall <notifications@github.com<mailto:notifications@github.com>>
> 
> wrote:
> 
> > Hmm. Looks like the $a_{lm}$'s are not available. The Planck Legacy
> > Archive documentation
> > <http://wiki.cosmos.esa.int/planckpla2015/index.php/Sky_temperature_maps
> > 
> > argue that we should be working from sky maps:
> > 
> > Sky maps give the best estimate of the intensity and polarization (Stokes
> > Q and U components), if available, of the signal from the sky after
> > removal, as far as possible, of known systematic effects (mostly
> > instrumental, but including also the solar and earth-motion dipole,
> > Galactic stray light and the Zodiacal light).
> > 
> > I think we should follow the prescription for computing the low ell
> > likelihood described here
> > <
> > http://wiki.cosmos.esa.int/planckpla2015/index.php/CMB_spectrum_%26_Likelihood_Code#Low-.E2.84.93_likelihoods
> > .
> > I'll download the baseline data and code
> > http://pla.esac.esa.int/pla/#cosmology and play around a bit.
> > @rkeisler
> > https://github.com/rkeisler, do you have python code for handling
> > Planck-formatted data? Looks like it'll be important to follow their
> > Healpix and FITS conventions.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rogerblandford/Music/issues/6#issuecomment-127287862
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/rogerblandford/Music/issues/6#issuecomment-127339144.

##

**Comment by drphilmarshall** [comment]
I agree. I got a good lead from Phil Bull, who says that the a_lm's exist
but not in public (insert political joke here). He said to ask "Eriksen"
for them - I'll try that!

Phil

**Comment by drphilmarshall** [comment]
Closed, see #7
